### ISSUE TITLE
Getting error with simple example code from docs

### ISSUE THREAD

**Issue by misteu** [column-street/InstaHashtag#1]
Hello!

Is this repo's code still up to date with the API or do I miss some package? I get an error but I am not sure what's going on.

I'm getting the error below, when testing with an example from your docs. My example code is this:

```python
from instahashtag import api

def io():
    """Uses 'requests' to send requests."""

    tag = api.tag(hashtag="instagram")
    graph = api.tag(hashtag="instagram")
    maps = api.maps(
        x1=-80.48712034709753,
        y1=25.750749758162012,
        x2=-79.82794065959753,
        y2=25.854604964203453,
        zoom=12,
    )

io()
```

The error is the following:
```bash
Traceback (most recent call last):
  File "/Users/michael.Steudter/Documents/pythonExperiments/displaypurposes/test.py", line 16, in <module>
    io()
  File "/Users/michael.Steudter/Documents/pythonExperiments/displaypurposes/test.py", line 6, in io
    tag = api.tag(hashtag="instagram")
  File "/Users/michael.Steudter/Documents/pythonExperiments/displaypurposes/venv/lib/python3.9/site-packages/instahashtag/api.py", line 43, in tag
    return http.Requests.tag(hashtag=hashtag)
  File "/Users/michael.Steudter/Documents/pythonExperiments/displaypurposes/venv/lib/python3.9/site-packages/instahashtag/http.py", line 103, in tag
    return obj.call()
  File "/Users/michael.Steudter/Documents/pythonExperiments/displaypurposes/venv/lib/python3.9/site-packages/instahashtag/http.py", line 133, in call
    return self.process(resp)
  File "/Users/michael.Steudter/Documents/pythonExperiments/displaypurposes/venv/lib/python3.9/site-packages/instahashtag/http.py", line 93, in process
    return json.loads(resp)
  File "/Applications/Xcode_14_1.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Applications/Xcode_14_1.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Applications/Xcode_14_1.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by misteu** [comment]
ok sorry, it seemed to have been an issue with my VPN setup.

However, the result still is always an empty array when calling like this:

```python
from instahashtag import Tag, Graph, Maps

tag = Tag(hashtag="plants")

print(tag.results)
```

Am I missing something? I'll do some further investigation with Postman later. Maybe the API changed or something?

**Comment by misteu** [comment]
Got it working now. The generated token was wrong. 

I just grabbed the original methods from the JS file you can find when using Firefox' inspector. The methods were mangled but when searching for "api-token" the right ones are easily found.

Then I just copied all the needed methods 1:1 into one .js file. As I'm using Swift, I'm just importing this file there and executing the JS function without caring to rewrite any of it.
